services:

  explorer:
    build: 
      context: explorer
    environment:
      VITE_SIMULATOR_RPC_URL: http://localhost:4000/api
    ports:
      - 5173:5173
    volumes:
      - ./explorer:/app
    depends_on:
      jsonrpc:
        condition: service_healthy

  # Simulator components

  postgres:
    image: postgres:16-alpine
    volumes:
      - .simulator-postgres:/var/lib/postgresql/data
    # ports:
    #   - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genlayer_state
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  jsonrpc:
    image: yeagerai/simulator-jsonrpc:v0.14.0-test001
    volumes:
      - ./.env.simulator:/app/.env
      - ./jsonrpc/healthcheck.py:/healthcheck.py
    environment:
      FLASK_SERVER_PORT: ${RPCPORT}
      # DISABLE_INFO_LOGS_ENDPOINTS: '["get_transaction_by_id","get_contract_schema_for_code","get_contract_schema", "ping"]'
      DISABLE_INFO_LOGS_ENDPOINTS: '["ping"]'
      OPENAIKEY: ${OPENAIKEY}
    depends_on:
      database-migration:
        condition: service_completed_successfully
    healthcheck:
      test: python /healthcheck.py --port ${RPCPORT}
      interval: 1s
      timeout: 1s
      retries: 15
      start_period: 1s
    ports:
      - ${RPCPORT}:${RPCPORT}

  database-migration:
    image: yeagerai/simulator-database-migration:v0.14.0-test001
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres/genlayer_state
    volumes:
      - ./.env.simulator:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
