services:

  frontend:
    build: 
      context: frontend
      target: dev
    environment:
      VITE_API_BASE_URL: http://localhost:8000/
    ports:
      - 5173:5173
      # - 8080:80 # nginx for build-test
    volumes:
      - ./frontend:/app

  # Simulator components

  postgres:
    image: postgres:16-alpine
    volumes:
      - .simulator-postgres:/var/lib/postgresql/data
    # ports:
    #   - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genlayer_state
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  jsonrpc:
    image: yeagerai/simulator-jsonrpc:v0.14.0-test001
    volumes:
      - ./.env.simulator:/app/.env
    environment:
      FLASK_SERVER_PORT: 4000
    depends_on:
      database-migration:
        condition: service_completed_successfully
    healthcheck: # TODO: Add a real healthcheck. This just waits 10 seconds
      test: exit 0
      interval: 10s
      timeout: 1s
      retries: 1
      start_period: 10s

  database-migration:
    image: yeagerai/simulator-database-migration:v0.14.0-test001
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres/genlayer_state
    volumes:
      - ./.env.simulator:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
